fix dashboard and flow stats polling
PrefectHQ/prefect-ui-library pull request #1598
Opened 2023-07-18 13:42 UTC by brandonreid

Removes the end date requirements for the dashboard and Flow Stats related mappers. That way when polling happens, they'll always fetch data up to the latest moment.

2023-07-18 13:46 UTC, brandonreid commented on src/components/FlowRunsBarChart.vue
> +  flex
I switched this to flex to remove the need to calculate columns, plus in a situation where for some reason more bars are trying to render than the width allows then the bars won't start wrapping, they'll just overflow to the side.

2023-07-18 14:05 UTC, pleek91 requested changes
Correct me if I'm wrong. But doesn't this change make it so as you leave the dashboard open the time span you're looking at grows? So 8 hours turns into 9 after leaving it open for an hour.

2023-07-18 14:07 UTC, brandonreid commented
> Correct me if I'm wrong. But doesn't this change make it so as you leave the dashboard open the time span you're looking at grows? So 8 hours turns into 9 after leaving it open for an hour.

That's correct. I called that out in the #raft-workspace-dashboard channel. It shou

2023-07-24 15:57 UTC, pleek91 commented
I'm going to close this PR in favor of implementing this change https://github.com/PrefectHQ/prefect-ui-library/pull/1602

That PR doesn't fix this but allows us to fix it without having the growing time span. I'll work on that today or tomorrow.

2023-07-24 15:57 UTC, closed without merging