Update flow run create forms to set `enforce_parameter_schema` on individual flow runs
PrefectHQ/prefect-ui-library pull request #2626
Opened 2024-07-24 15:02 UTC by pleek91

# Description
UI side of https://github.com/PrefectHQ/prefect/pull/14718

Updates the "validate parameters before submitting" checkbox and its logic. 

- Changes the label to "Enforce parameter schema"
- Defaults to the value of the deployment's setting for `enforce_parameter_schema`
- Toggling the checkbox sets the value for `enforce_parameter_schema` on the flow run create request
- Unchecking the checkbox (or leaving it unchecked if the deployment defaults it to unchecked) will prevent all parameter validation (both when submitting and when the run is scheduled)

2024-07-24 16:53 UTC, cicdw requested changes
small nit: i think the user-facing name for this should still be "validate" but the rest LGTM, thank you!

2024-07-24 16:53 UTC, cicdw commented on src/components/FlowRunCreateForm.vue
> +          <p-checkbox v-model="enforceParameterSchema" label="Enforce parameter schema" />
I kind of like "Validate" better than "Enforce"; it implies there's a failure mode associated with it

```suggestion
          <p-checkbox v-model="enforceParameterSchema" label="Validate parameters" />
```

2024-07-24 16:53 UTC, cicdw commented on src/components/QuickRunParametersModal.vue
> +        <p-checkbox v-model="enforceParameterSchema" label="Enforce parameter schema" />
ah i see here as well should be "validate"

2024-07-24 17:34 UTC, cicdw approved these changes

2024-07-25 14:45 UTC, znicholasbrown approved these changes

2024-07-25 14:45 UTC, znicholasbrown commented on src/services/WorkspaceDeploymentsApi.ts
> +  public async createDeployment(deployment: DeploymentCreate): Promise<Deployment> {
subtle

2024-07-25 16:32 UTC, merged